server:
  port: 8761               # 执行服务端口（默认 Eureka Server 就是8761）
spring:
  application:
    name: EUREKASERVER     # 指定服务名称（唯一标识，注意：服务名不能出现下划线，默认服务名不区分大小写，推荐服务名大写）
eureka:
  instance:
    hostname: localhost    # 主机名称
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/    # 指定服务注册中心的地址（如果是集群则添加多个地址，用逗号分割）
      fetch-registry: false                # 关闭作为客户端时从 eureka server 获取服务信息
      register-with-eureka: false          # 不再将自己同时作为客户端进行注册
  sever:
    enable-self-preservation: false        # 关闭自我保护（官方不建议）
    eviction-interval-timer-in-ms: 3000    # 超时 3s 自动清除
